#!/usr/bin/env python3
"""Detect host-matrix pointer drift across every adapter repository.

``dcc-mcp-catalog.yml`` in this repository is the single source of truth for the
host matrix. Each adapter README carries a block generated by
``generate_adapter_pointer.py`` that quotes the adapter count, so a catalog
edit that is not followed by a regeneration in every adapter repository leaves
the ecosystem describing a host list that no longer exists.

``generate_adapter_pointer.py apply --check`` already knows how to verify one
repository; it needs a checkout of that repository and the catalog. What was
missing was the thing that walks all 47 of them. This script is that walk: it
clones each adapter repository at its default branch, replays the generator
against the README it finds there, and reports any repository whose block is
missing or no longer equal to what the catalog produces today.

It is read-only with respect to the adapter repositories. It never opens a pull
request and never pushes; a drifted repository is reported so a human or a
follow-up job can regenerate it.

Usage
-----
    # Scan every adapter in the catalog (network; ~47 clones).
    python scripts/check_adapter_pointer_drift.py

    # Limit the walk and emit a Markdown summary for a job summary.
    python scripts/check_adapter_pointer_drift.py --only dcc-mcp-maya,dcc-mcp-krita --summary

Exit codes
----------
0   every scanned repository is current (or was skipped, and skipping is allowed)
1   at least one repository is drifted or unreadable
2   the catalog or the arguments could not be used at all

Only the git subprocesses and the catalog read touch the outside world; no
PyPI or other HTTP service is involved, so the check needs no secrets beyond
whatever the runner already uses to clone public repositories.
"""

from __future__ import annotations

import argparse
import contextlib
import json
import os
from pathlib import Path
import shutil
import stat
import subprocess
import sys
import tempfile

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from scripts import generate_adapter_pointer as generator  # noqa: E402

DEFAULT_TIMEOUT_SECS = 300
_REFS_HEADS = "refs/heads/"

DRIFTED = "drifted"
CURRENT = "current"
MISSING = "missing"
ERROR = "error"


class ScanError(RuntimeError):
    """Raised when the scan itself cannot start."""


def _git(args: list[str], *, timeout: int) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args],
        capture_output=True,
        text=True,
        timeout=timeout,
        check=False,
    )


def _clone_default_branch(url: str, dest: Path, *, timeout: int, depth: int = 1) -> str:
    """Shallow-clone ``url`` at its default branch and return the branch name.

    ``--depth 1`` keeps the walk cheap: the check only ever reads the README as
    it stands on the default branch, so history has no bearing on the verdict.
    """
    result = _git(
        [
            "clone",
            "--quiet",
            "--depth",
            str(depth),
            "--no-tags",
            "--single-branch",
            url,
            str(dest),
        ],
        timeout=timeout,
    )
    if result.returncode != 0:
        message = (result.stderr or result.stdout).strip().splitlines()
        raise ScanError(f"clone failed for {url}: {message[-1] if message else 'no output'}")

    branch = _git(["-C", str(dest), "rev-parse", "--abbrev-ref", "HEAD"], timeout=timeout)
    if branch.returncode != 0 or not branch.stdout.strip():
        raise ScanError(f"could not resolve the default branch of {url}")
    return branch.stdout.strip()


def _default_branch_name(url: str, *, timeout: int) -> str:
    """Ask the remote which branch HEAD points at, without cloning."""
    result = _git(["ls-remote", "--symref", url, "HEAD"], timeout=timeout)
    if result.returncode != 0:
        return ""
    for line in result.stdout.splitlines():
        if line.startswith("ref:") and "\tHEAD" in line:
            ref = line.split()[1]
            # `str.removeprefix` is 3.9+; this repository supports 3.7.
            return ref[len(_REFS_HEADS) :] if ref.startswith(_REFS_HEADS) else ref
    return ""


def check_repository(
    entry: dict,
    entry_index: int,
    *,
    host_count: int,
    workdir: Path,
    timeout: int,
) -> dict:
    """Replay the generator against one adapter repository on its default branch."""
    name = str(entry.get("name") or "").strip() or f"<entry {entry_index}>"
    url = str(entry.get("url") or "").strip()
    row = {
        "name": name,
        "url": url,
        "status": ERROR,
        "branch": "",
        "detail": "",
    }

    if not url:
        row["detail"] = "catalog entry has no `url`; nothing to scan"
        return row

    repo_dir = workdir / _safe_dirname(name, entry_index)
    row["branch"] = _default_branch_name(url, timeout=timeout)

    try:
        branch = _clone_default_branch(url, repo_dir, timeout=timeout)
        if branch:
            row["branch"] = branch
        readme = repo_dir / "README.md"
        if not readme.is_file():
            row["status"] = MISSING
            row["detail"] = "no README.md on the default branch"
            return row

        # newline="" so a CRLF README is compared in its own line endings; the
        # generator preserves them, and translating here would report drift for
        # every Windows-authored README.
        with readme.open(encoding="utf-8", newline="") as handle:
            original = handle.read()

        if generator.POINTER_START not in original:
            row["status"] = MISSING
            row["detail"] = "README carries no generated pointer block"
            return row

        expected = generator.upsert_pointer(original, generator.render_pointer(entry, host_count=host_count))
        if expected != original:
            row["status"] = DRIFTED
            row["detail"] = "pointer block does not match the current catalog output"
            return row

        row["status"] = CURRENT
        row["detail"] = f"matches the catalog output ({host_count} adapters)"
        return row
    except Exception as exc:
        # Broad on purpose. This loop walks ~47 repositories owned by other
        # teams, so any one of them can fail in a way this script did not
        # anticipate: a README that is not valid UTF-8, a path that will not
        # decode, a disk or permission error, a git binary that is missing.
        # Letting one of those escape would abort the whole run before the
        # summary and the JSON report are written, so the remaining 46
        # repositories would silently go unchecked. A repository this cannot
        # read is reported as an error, never raised.
        row["status"] = ERROR
        row["detail"] = f"{type(exc).__name__}: {exc}".strip()
        return row
    finally:
        _remove_clone(repo_dir)


def _on_rmtree_error(func, path: str, exc_info) -> None:
    """Clear the read-only bit and retry when Windows refuses to unlink a file.

    Git marks the files under ``.git/objects`` read-only when it writes a
    pack. On Windows a read-only file cannot be unlinked, so a plain
    ``shutil.rmtree`` on a shallow clone leaves the whole ``.git`` directory
    behind with ``WinError 5``. Forty-seven clones per run would otherwise
    accumulate in the runner's temp directory.
    """
    target = Path(path)
    if not target.exists():
        return
    try:
        target.chmod(stat.S_IWRITE)
    except OSError:
        return
    with contextlib.suppress(OSError):
        func(path)


def _remove_clone(path: Path) -> None:
    shutil.rmtree(path, onerror=_on_rmtree_error)


def _safe_dirname(name: str, index: int) -> str:
    """Make a filesystem-safe, collision-free directory name for one clone."""
    cleaned = "".join(char if char.isalnum() or char in "._-" else "_" for char in name)
    return f"{index:03d}-{cleaned or 'adapter'}"


def scan(
    entries: list[dict],
    *,
    workdir: Path,
    only: set[str] | None = None,
    timeout: int = DEFAULT_TIMEOUT_SECS,
) -> list[dict]:
    """Scan every catalog adapter entry, or the subset named by ``only``."""
    host_count = len(entries)
    results = []
    for index, entry in enumerate(entries):
        name = str(entry.get("name") or "").strip()
        if only is not None and name.lower() not in only:
            continue
        results.append(
            check_repository(
                entry,
                index,
                host_count=host_count,
                workdir=workdir,
                timeout=timeout,
            )
        )
    return results


def _github_annotation(row: dict) -> None:
    print(f"::error title=pointer drift in {row['name']}::{row['detail']} ({row['url']})")


def render_summary(results: list[dict], *, host_count: int) -> str:
    """Render a Markdown table for a GitHub job summary."""
    lines = [
        "## Adapter pointer drift",
        "",
        f"Catalog adapter count: **{host_count}**",
        "",
        "| Adapter | Status | Branch | Detail |",
        "|---|---|---|---|",
    ]
    for row in results:
        lines.append(f"| `{row['name']}` | {row['status']} | {row['branch'] or '—'} | {row['detail']} |")

    # Counted by status, not by `!= CURRENT`: a repository that could not be
    # cloned or read is an infrastructure problem, not drift, and telling
    # someone to regenerate the block in it is the wrong instruction.
    drifted = [r for r in results if r["status"] == DRIFTED]
    missing = [r for r in results if r["status"] == MISSING]
    errored = [r for r in results if r["status"] == ERROR]

    lines.append("")
    if drifted:
        lines.append(
            f"**{len(drifted)} of {len(results)} repositories drift from the catalog.**"
            " Run `generate_adapter_pointer.py apply` in each one, or the batch job"
            " that does it for you."
        )
    else:
        lines.append(f"All {len(results)} scanned repositories match the catalog output.")
    if missing:
        lines.append("")
        lines.append(
            f"{len(missing)} repositories carry no generated block at all. That is a"
            " separate backlog from the count drift; re-run the generator in each of"
            " them to add it."
        )
    if errored:
        lines.append("")
        lines.append(
            f"{len(errored)} repositories could not be read (clone, decode or I/O"
            " failure). These need infrastructure attention, not a regeneration."
        )
    lines.append("")
    return "\n".join(lines)


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--catalog",
        type=Path,
        default=REPO_ROOT / "dcc-mcp-catalog.yml",
        help="Path to dcc-mcp-catalog.yml (default: the catalog in this repository).",
    )
    parser.add_argument(
        "--only",
        help="Comma-separated adapter names to scan; default is every catalog adapter.",
    )
    parser.add_argument(
        "--workdir",
        type=Path,
        help="Directory for the temporary clones (default: a fresh temp directory).",
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=DEFAULT_TIMEOUT_SECS,
        help=f"Per-git-operation timeout in seconds (default: {DEFAULT_TIMEOUT_SECS}).",
    )
    parser.add_argument(
        "--summary",
        action="store_true",
        help="Write a Markdown summary to $GITHUB_STEP_SUMMARY when it is set.",
    )
    parser.add_argument(
        "--json-out",
        type=Path,
        help="Write the per-repository result rows to this path as JSON.",
    )
    parser.add_argument(
        "--allow-missing",
        action="store_true",
        help="Treat a missing README or pointer block as acceptable instead of a failure.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    """Scan adapter repositories and return 1 when any of them has drifted."""
    args = _build_parser().parse_args(argv)

    try:
        catalog = generator.load_catalog(args.catalog)
    except generator.CoverageError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    entries = generator.adapter_entries(catalog)
    if not entries:
        print(f"error: {args.catalog} contains no adapter entries", file=sys.stderr)
        return 2

    only = None
    if args.only:
        only = {part.strip().lower() for part in args.only.split(",") if part.strip()}
        known = {str(e.get("name", "")).strip().lower() for e in entries}
        unknown = sorted(only - known)
        if unknown:
            print(f"error: catalog has no adapter named {unknown}", file=sys.stderr)
            return 2

    host_count = len(entries)
    managed = tempfile.TemporaryDirectory(prefix="adapter-pointer-drift-")
    try:
        workdir = args.workdir or Path(managed.name)
        workdir.mkdir(parents=True, exist_ok=True)
        results = scan(entries, workdir=workdir, only=only, timeout=args.timeout)
    finally:
        managed.cleanup()

    for row in results:
        marker = "ok  " if row["status"] == CURRENT else "FAIL"
        print(f"{marker} {row['name']:<32} {row['status']:<8} {row['detail']}")

    drifted = [r for r in results if r["status"] == DRIFTED]
    missing = [r for r in results if r["status"] == MISSING]
    errored = [r for r in results if r["status"] == ERROR]

    if drifted or errored or (missing and not args.allow_missing):
        for row in [*drifted, *errored, *([] if args.allow_missing else missing)]:
            _github_annotation(row)

    summary = render_summary(results, host_count=host_count)
    if args.summary:
        summary_path = os.environ.get("GITHUB_STEP_SUMMARY")
        if summary_path:
            with Path(summary_path).open("a", encoding="utf-8") as handle:
                handle.write(summary)
        else:
            print()
            print(summary)

    if args.json_out:
        args.json_out.parent.mkdir(parents=True, exist_ok=True)
        args.json_out.write_text(
            json.dumps(
                {"adapter_count": host_count, "results": results},
                indent=2,
                ensure_ascii=False,
            )
            + "\n",
            encoding="utf-8",
        )

    print()
    print(
        f"{len(results)} repositories scanned against a catalog of {host_count} adapters:"
        f" {len(drifted)} drifted, {len(missing)} missing, {len(errored)} unreadable."
    )
    if drifted or errored or (missing and not args.allow_missing):
        print(
            "Drifted repositories quote a host count the catalog no longer produces."
            " Re-run `generate_adapter_pointer.py apply` in each of them."
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
