//! Python-visible MCP HTTP server configuration.

use super::*;
use std::collections::HashMap;

mod build;

/// Python-visible MCP HTTP server configuration.
///
/// Example::
///
///     from dcc_mcp_core import McpHttpConfig
///     config = McpHttpConfig(port=8765, server_name="my-dcc")
///
/// Mechanical accessors are generated by `PyWrapper`, including nested
/// aggregate paths introduced when `McpHttpConfig` was split into cohesive
/// sub-config structs (issue #764). Conversions and validation stay explicit.
///
/// Non-trivial conversions (enum/path/map/repr) stay explicit in the
/// `#[pymethods]` block so Python errors remain precise.
#[pyclass(name = "McpHttpConfig", skip_from_py_object)]
#[derive(dcc_mcp_pybridge::derive::PyWrapper)]
#[py_wrapper(
    inner = "McpHttpConfig",
    fields(
        /// Port the server listens on.
        port => server.port: u16 => [get],
        /// IP address the server binds to.
        host => server.host: String => [get(to_string)],
        /// MCP endpoint path.
        endpoint_path => server.endpoint_path: String => [get(clone)],
        /// Server name reported during initialization.
        server_name => server.server_name: String => [get(clone)],
        /// Server version reported during initialization.
        server_version => server.server_version: String => [get(clone)],
        /// Maximum concurrent SSE sessions.
        max_sessions => server.max_sessions: usize => [get],
        /// Request timeout in milliseconds.
        request_timeout_ms => server.request_timeout_ms: u64 => [get],
        /// Whether CORS is enabled.
        enable_cors => server.enable_cors: bool => [get],
        /// Idle session TTL in seconds.
        session_ttl_secs => session.session_ttl_secs: u64 => [get, set],
        /// Whether connection-scoped tool-list caching is enabled.
        enable_tool_cache => session.enable_tool_cache: bool => [get, set],
        /// Enable the Prometheus endpoint.
        enable_prometheus => telemetry.enable_prometheus: bool => [get, set],
        /// Optional HTTP Basic auth for Prometheus.
        prometheus_basic_auth => telemetry.prometheus_basic_auth: Option<(String, String)> => [get(clone), set],
        /// Enable lazy actions.
        lazy_actions => features.lazy_actions: bool => [get, set],
        /// Enable built-in workflows.
        enable_workflows => workflow.enable_workflows: bool => [get, set],
        /// Shut down the server handle when dropped.
        shutdown_on_drop => features.shutdown_on_drop: bool => [get, set],
        /// Emit job update notifications.
        enable_job_notifications => features.enable_job_notifications: bool => [get, set],
        /// Publish unique actions under bare names.
        bare_tool_names => features.bare_tool_names: bool => [get, set],
        /// Exclude unloaded-skill stubs from tools/list.
        exclude_skill_stubs_from_tools_list => features.exclude_skill_stubs_from_tools_list: bool => [get, set],
        /// Exclude inactive-group stubs from tools/list.
        exclude_group_stubs_from_tools_list => features.exclude_group_stubs_from_tools_list: bool => [get, set],
        /// Advertise MCP resources.
        enable_resources => features.enable_resources: bool => [get, set],
        /// Expose artefact resources.
        enable_artefact_resources => features.enable_artefact_resources: bool => [get, set],
        /// Advertise MCP prompts.
        enable_prompts => features.enable_prompts: bool => [get, set],
        /// Treat the standalone interpreter as the main-thread lane.
        standalone_main_thread_execution => features.standalone_main_thread_execution: bool => [get, set],
        /// Gateway election port.
        gateway_port => gateway.gateway_port: u16 => [get, set],
        /// Optional remote gateway bind host.
        gateway_remote_host => gateway.remote_host: Option<String> => [get(clone), set],
        /// Optional remote gateway port.
        gateway_remote_port => gateway.remote_gateway_port: u16 => [get, set],
        /// Enable the gateway admin dashboard.
        admin_enabled => gateway.admin_enabled: bool => [get, set],
        /// Gateway admin URL prefix.
        admin_path => gateway.admin_path: String => [get(clone), set],
        /// Registry stale timeout in seconds.
        stale_timeout_secs => gateway.stale_timeout_secs: u64 => [get, set],
        /// Registry heartbeat interval in seconds.
        heartbeat_secs => gateway.heartbeat_secs: u64 => [get, set],
        /// Per-backend request timeout in milliseconds.
        backend_timeout_ms => gateway.backend_timeout_ms: u64 => [get, set],
        /// Async dispatch timeout in milliseconds.
        gateway_async_dispatch_timeout_ms => gateway.gateway_async_dispatch_timeout_ms: u64 => [get, set],
        /// Wait-for-terminal timeout in milliseconds.
        gateway_wait_terminal_timeout_ms => gateway.gateway_wait_terminal_timeout_ms: u64 => [get, set],
        /// Gateway job-route TTL in seconds.
        gateway_route_ttl_secs => gateway.gateway_route_ttl_secs: u64 => [get, set],
        /// Per-session gateway route ceiling.
        gateway_max_routes_per_session => gateway.gateway_max_routes_per_session: u64 => [get, set],
        /// Adapter package version.
        adapter_version => gateway.adapter_version: Option<String> => [get(clone), set],
        /// Adapter DCC type.
        adapter_dcc => gateway.adapter_dcc: Option<String> => [get(clone), set],
        /// Gateway candidate name.
        gateway_name => gateway.gateway_name: Option<String> => [get(clone), set],
        /// Allow unknown DCC tools.
        allow_unknown_tools => gateway.allow_unknown_tools: bool => [get, set],
        /// Enable read-only gateway policy.
        gateway_read_only => gateway.policy.read_only: bool => [get, set],
        /// Allowed gateway DCC types.
        allowed_dcc_types => gateway.policy.allowed_dcc_types: Vec<String> => [get(clone), set],
        /// Allowed gateway skill names.
        allowed_skill_names => gateway.policy.allowed_skill_names: Vec<String> => [get(clone), set],
        /// Allowed gateway skill families.
        allowed_skill_families => gateway.policy.allowed_skill_families: Vec<String> => [get(clone), set],
        /// Allowed canonical tool slugs.
        allowed_tool_slugs => gateway.policy.allowed_tool_slugs: Vec<String> => [get(clone), set],
        /// Allowed canonical tool slug prefixes.
        allowed_tool_slug_prefixes => gateway.policy.allowed_tool_slug_prefixes: Vec<String> => [get(clone), set],
        /// Deferred execution queue depth.
        deferred_queue_depth => queue.deferred_queue_depth: usize => [get, set],
        /// Bridge queue depth.
        bridge_queue_depth => queue.bridge_queue_depth: usize => [get, set],
        /// Host queue depth.
        host_queue_depth => queue.host_queue_depth: usize => [get, set],
        /// Queue send timeout in milliseconds.
        queue_send_timeout_ms => queue.queue_send_timeout_ms: u64 => [get, set],
        /// Optional host process ID.
        host_pid => instance.host_pid: Option<u32> => [get, set],
        /// Optional DCC type.
        dcc_type => instance.dcc_type: Option<String> => [get(clone), set],
        /// Optional DCC version.
        dcc_version => instance.dcc_version: Option<String> => [get(clone), set],
        /// Optional scene name.
        scene => instance.scene: Option<String> => [get(clone), set],
        /// Declared instance capabilities.
        declared_capabilities => instance.declared_capabilities: Vec<String> => [get(clone), set],
        /// Free-form instance metadata.
        instance_metadata => instance.instance_metadata: HashMap<String, String> => [get(clone), set],
        /// Enable the scheduler.
        enable_scheduler => workflow.enable_scheduler: bool => [get, set],
        /// HTTP self-probe timeout in milliseconds.
        self_probe_timeout_ms => server.self_probe_timeout_ms: u64 => [get, set],
    ),
)]
pub struct PyMcpHttpConfig {
    pub(crate) inner: McpHttpConfig,
    /// Optional :class:`SandboxPolicy` forwarded to the in-process executor (issue #1001).
    sandbox_policy: Option<Py<PyAny>>,
}

impl Clone for PyMcpHttpConfig {
    fn clone(&self) -> Self {
        Python::try_attach(|py| Self {
            inner: self.inner.clone(),
            sandbox_policy: self
                .sandbox_policy
                .as_ref()
                .map(|policy| policy.clone_ref(py)),
        })
        .unwrap_or_else(|| Self {
            inner: self.inner.clone(),
            sandbox_policy: None,
        })
    }
}

impl From<McpHttpConfig> for PyMcpHttpConfig {
    fn from(inner: McpHttpConfig) -> Self {
        Self {
            inner,
            sandbox_policy: None,
        }
    }
}

#[pymethods]
impl PyMcpHttpConfig {
    /// Create a new config. ``port=0`` binds to any available port.
    #[new]
    #[pyo3(signature = (port=0, server_name=None, server_version=None, enable_cors=false, request_timeout_ms=30000, backend_timeout_ms=120_000, enable_prometheus=false, prometheus_basic_auth=None, gateway_async_dispatch_timeout_ms=60_000, gateway_wait_terminal_timeout_ms=600_000, gateway_route_ttl_secs=86_400, gateway_max_routes_per_session=1_000, shutdown_on_drop=false))]
    #[allow(clippy::too_many_arguments)]
    fn new(
        port: u16,
        server_name: Option<String>,
        server_version: Option<String>,
        enable_cors: bool,
        request_timeout_ms: u64,
        backend_timeout_ms: u64,
        enable_prometheus: bool,
        prometheus_basic_auth: Option<(String, String)>,
        gateway_async_dispatch_timeout_ms: u64,
        gateway_wait_terminal_timeout_ms: u64,
        gateway_route_ttl_secs: u64,
        gateway_max_routes_per_session: u64,
        shutdown_on_drop: bool,
    ) -> Self {
        Self {
            inner: build::build_config(
                port,
                server_name,
                server_version,
                enable_cors,
                request_timeout_ms,
                backend_timeout_ms,
                enable_prometheus,
                prometheus_basic_auth,
                gateway_async_dispatch_timeout_ms,
                gateway_wait_terminal_timeout_ms,
                gateway_route_ttl_secs,
                gateway_max_routes_per_session,
                shutdown_on_drop,
            ),
            sandbox_policy: None,
        }
    }

    /// Optional sandbox policy applied to in-process skill execution (issue #1001).
    #[getter]
    fn sandbox_policy(&self, py: Python<'_>) -> Option<Py<PyAny>> {
        self.sandbox_policy.as_ref().map(|p| p.clone_ref(py))
    }

    #[setter]
    fn set_sandbox_policy(&mut self, policy: Option<Py<PyAny>>) {
        self.sandbox_policy = policy;
    }

    /// Bind address. Accepts any IPv4/IPv6 literal that ``std::net::IpAddr``
    /// can parse. Raises ``ValueError`` for malformed input — never panics.
    #[setter]
    fn set_host(&mut self, v: &str) -> PyResult<()> {
        self.inner.set_host(v).map(|_| ()).map_err(|e| {
            pyo3::exceptions::PyValueError::new_err(format!("invalid host {v:?}: {e}"))
        })
    }

    /// Directory holding ``*.schedules.yaml`` files (issue #352).
    #[getter]
    fn schedules_dir(&self) -> Option<String> {
        self.inner
            .workflow
            .schedules_dir
            .as_ref()
            .map(|p| p.to_string_lossy().to_string())
    }

    /// Directory holding ``*.schedules.yaml`` files (issue #352).
    #[setter]
    fn set_schedules_dir(&mut self, v: Option<String>) {
        self.inner.workflow.schedules_dir = v.map(std::path::PathBuf::from);
    }

    // ── Hand-written special accessors ──────────────────────────────

    /// Optional filesystem path to a SQLite database for job persistence (issue #328).
    #[getter]
    fn job_storage_path(&self) -> Option<String> {
        self.inner
            .job
            .job_storage_path
            .as_ref()
            .map(|p| p.to_string_lossy().to_string())
    }

    /// Optional filesystem path to a SQLite database for job persistence (issue #328).
    #[setter]
    fn set_job_storage_path(&mut self, path: Option<String>) {
        self.inner.job.job_storage_path = path.map(std::path::PathBuf::from);
    }

    /// Shared FileRegistry directory path. ``None`` uses a system temp dir.
    #[getter]
    fn registry_dir(&self) -> Option<String> {
        self.inner
            .gateway
            .registry_dir
            .as_ref()
            .map(|p| p.to_string_lossy().to_string())
    }

    /// Shared FileRegistry directory path. ``None`` uses a system temp dir.
    #[setter]
    fn set_registry_dir(&mut self, dir: Option<String>) {
        self.inner.gateway.registry_dir = dir.map(std::path::PathBuf::from);
    }

    /// Listener spawn strategy (issue #303).
    #[getter]
    fn spawn_mode(&self) -> &'static str {
        match self.inner.server.spawn_mode {
            ServerSpawnMode::Ambient => "ambient",
            ServerSpawnMode::Dedicated => "dedicated",
        }
    }

    /// Listener spawn strategy (issue #303).
    #[setter]
    fn set_spawn_mode(&mut self, mode: &str) -> PyResult<()> {
        self.inner.server.spawn_mode = match mode {
            "ambient" => ServerSpawnMode::Ambient,
            "dedicated" => ServerSpawnMode::Dedicated,
            other => {
                return Err(pyo3::exceptions::PyValueError::new_err(format!(
                    "spawn_mode must be 'ambient' or 'dedicated', got {other:?}"
                )));
            }
        };
        Ok(())
    }

    /// Lower-case wire identifier of the configured job-recovery policy (issue #567).
    #[getter]
    fn job_recovery(&self) -> &'static str {
        self.inner.job.job_recovery.as_str()
    }

    /// Lower-case wire identifier of the configured job-recovery policy (issue #567).
    #[setter]
    fn set_job_recovery(&mut self, policy: &str) -> PyResult<()> {
        self.inner.job.job_recovery = dcc_mcp_http_types::config::JobRecoveryPolicy::parse(policy)
            .map_err(pyo3::exceptions::PyValueError::new_err)?;
        Ok(())
    }

    // ── __repr__ ────────────────────────────────────────────────────

    fn __repr__(&self) -> String {
        dcc_mcp_pybridge::repr_pairs!(
            "McpHttpConfig",
            [
                ("port", self.inner.server.port),
                ("name", self.inner.server.server_name),
                ("gateway_port", self.inner.gateway.gateway_port),
            ]
        )
    }
}

#[cfg(test)]
mod tests;
