"""Shared string constants used by the Python runtime (#487, #2196).

Centralises DCC-MCP environment names, metadata keys, SKILL layer names,
and tool categories that would otherwise be duplicated across modules.

Renaming a key now means editing one line here instead of grepping the
whole codebase.
"""

from __future__ import annotations

ENV_API_KEY: str = "DCC_MCP_API_KEY"
ENV_ASSET: str = "DCC_MCP_ASSET"
ENV_ASSET_TYPE: str = "DCC_MCP_ASSET_TYPE"
ENV_CONTEXT_BUNDLE: str = "DCC_MCP_CONTEXT_BUNDLE"
ENV_CONTEXT_KIND: str = "DCC_MCP_CONTEXT_KIND"
ENV_CORE_VERSION: str = "DCC_MCP_CORE_VERSION"
ENV_CUA_ALLOW_RAW_INPUT: str = "DCC_MCP_CUA_ALLOW_RAW_INPUT"
ENV_CUA_BINARY: str = "DCC_MCP_CUA_BINARY"
ENV_MCP_INSTALL_DIR: str = "DCC_MCP_INSTALL_DIR"
ENV_DAEMONIZED: str = "DCC_MCP__DAEMONIZED"
ENV_DCC_EXCLUDE_STUBS_FROM_TOOLS_LIST_TEMPLATE: str = "DCC_MCP_{}_EXCLUDE_STUBS_FROM_TOOLS_LIST"
ENV_DCC_INSTANCE_TYPE_TEMPLATE: str = "DCC_MCP_{}_INSTANCE_TYPE"
ENV_DCC_PORT_TEMPLATE: str = "DCC_MCP_{}_PORT"
ENV_DCC_SKILL_PATHS_TEMPLATE: str = "DCC_MCP_{}_SKILL_PATHS"
ENV_DCC_TYPE: str = "DCC_MCP_DCC_TYPE"
ENV_DEFAULT_TOOLS: str = "DCC_MCP_DEFAULT_TOOLS"
ENV_DEPLOYMENT_MODE: str = "DCC_MCP_DEPLOYMENT_MODE"
ENV_DISABLE_ACCUMULATED_SKILLS: str = "DCC_MCP_DISABLE_ACCUMULATED_SKILLS"
ENV_DISABLE_DEFAULT_SKILL_PATHS: str = "DCC_MCP_DISABLE_DEFAULT_SKILL_PATHS"
ENV_DISABLE_FILE_LOGGING: str = "DCC_MCP_DISABLE_FILE_LOGGING"
ENV_DISABLE_JOB_PERSISTENCE: str = "DCC_MCP_DISABLE_JOB_PERSISTENCE"
ENV_DISABLE_TELEMETRY: str = "DCC_MCP_DISABLE_TELEMETRY"
ENV_EMBED_MODEL: str = "DCC_MCP_EMBED_MODEL"
ENV_EMBED_MODEL_DIR: str = "DCC_MCP_EMBED_MODEL_DIR"
ENV_EXCLUDE_STUBS_FROM_TOOLS_LIST: str = "DCC_MCP_EXCLUDE_STUBS_FROM_TOOLS_LIST"
ENV_GATEWAY_ADMIN_DB: str = "DCC_MCP_GATEWAY_ADMIN_DB"
ENV_GATEWAY_ENSURE_TIMEOUT_SECS: str = "DCC_MCP_GATEWAY_ENSURE_TIMEOUT_SECS"
ENV_GATEWAY_GUARDIAN_FAILURES: str = "DCC_MCP_GATEWAY_GUARDIAN_FAILURES"
ENV_GATEWAY_GUARDIAN_INTERVAL: str = "DCC_MCP_GATEWAY_GUARDIAN_INTERVAL"
ENV_GATEWAY_GUARDIAN_REENSURE_JITTER_MAX: str = "DCC_MCP_GATEWAY_GUARDIAN_REENSURE_JITTER_MAX"
ENV_GATEWAY_GUARDIAN_RESTART_TIMEOUT: str = "DCC_MCP_GATEWAY_GUARDIAN_RESTART_TIMEOUT"
ENV_GATEWAY_GUARDIAN_TIMEOUT: str = "DCC_MCP_GATEWAY_GUARDIAN_TIMEOUT"
ENV_GATEWAY_HOST: str = "DCC_MCP_GATEWAY_HOST"
ENV_GATEWAY_IDLE_TIMEOUT_SECS: str = "DCC_MCP_GATEWAY_IDLE_TIMEOUT_SECS"
ENV_GATEWAY_LAUNCH_LOCK_STALE_SECS: str = "DCC_MCP_GATEWAY_LAUNCH_LOCK_STALE_SECS"
ENV_GATEWAY_NAME: str = "DCC_MCP_GATEWAY_NAME"
ENV_GATEWAY_PERSIST: str = "DCC_MCP_GATEWAY_PERSIST"
ENV_GATEWAY_PORT: str = "DCC_MCP_GATEWAY_PORT"
ENV_GATEWAY_PROBE_FAILURES: str = "DCC_MCP_GATEWAY_PROBE_FAILURES"
ENV_GATEWAY_PROBE_INTERVAL: str = "DCC_MCP_GATEWAY_PROBE_INTERVAL"
ENV_GATEWAY_PROBE_TIMEOUT: str = "DCC_MCP_GATEWAY_PROBE_TIMEOUT"
ENV_GUARDIAN_WATCHDOG_INTERVAL: str = "DCC_MCP_GUARDIAN_WATCHDOG_INTERVAL"
ENV_HOST_RPC: str = "DCC_MCP_HOST_RPC"
ENV_INSTANCE_TYPE: str = "DCC_MCP_INSTANCE_TYPE"
ENV_IPC_ADDRESS: str = "DCC_MCP_IPC_ADDRESS"
ENV_LOG_DIR: str = "DCC_MCP_LOG_DIR"
ENV_MARKETPLACE_INSTALL_ROOT: str = "DCC_MCP_MARKETPLACE_INSTALL_ROOT"
ENV_MINIMAL: str = "DCC_MCP_MINIMAL"
ENV_PACKAGE_PROVENANCE: str = "DCC_MCP_PACKAGE_PROVENANCE"
ENV_PRODUCTION_DOMAIN: str = "DCC_MCP_PRODUCTION_DOMAIN"
ENV_PROJECT: str = "DCC_MCP_PROJECT"
ENV_PROMPT_PATHS: str = "DCC_MCP_PROMPT_PATHS"
ENV_PYTHON_EXECUTABLE: str = "DCC_MCP_PYTHON_EXECUTABLE"
ENV_REGISTRY_DIR: str = "DCC_MCP_REGISTRY_DIR"
ENV_RESOURCE_PATHS: str = "DCC_MCP_RESOURCE_PATHS"
ENV_REZ_LOCAL_CACHE_ROOT: str = "DCC_MCP_REZ_LOCAL_CACHE_ROOT"
ENV_SCRIPT_MATERIALIZATION_ROOT: str = "DCC_MCP_SCRIPT_MATERIALIZATION_ROOT"
ENV_SEQUENCE: str = "DCC_MCP_SEQUENCE"
ENV_SERVER_BIN: str = "DCC_MCP_SERVER_BIN"
ENV_SHOT: str = "DCC_MCP_SHOT"
ENV_SKILL_PATHS: str = "DCC_MCP_SKILL_PATHS"
ENV_STRICT_GATEWAY: str = "DCC_MCP_STRICT_GATEWAY"
ENV_TASK: str = "DCC_MCP_TASK"
ENV_TEAM_DCC_SKILL_PATHS_TEMPLATE: str = "DCC_MCP_TEAM_{}_SKILL_PATHS"
ENV_TEAM_SKILL_PATHS: str = "DCC_MCP_TEAM_SKILL_PATHS"
ENV_TOOLSET_PROFILE: str = "DCC_MCP_TOOLSET_PROFILE"
ENV_UI_CONTROL_BACKEND: str = "DCC_MCP_UI_CONTROL_BACKEND"
ENV_UI_CONTROL_DCC_TYPE: str = "DCC_MCP_UI_CONTROL_DCC_TYPE"
ENV_UI_CONTROL_PROCESS_ID: str = "DCC_MCP_UI_CONTROL_PROCESS_ID"
ENV_UI_CONTROL_WINDOW_HANDLE: str = "DCC_MCP_UI_CONTROL_WINDOW_HANDLE"
ENV_USER_DCC_SKILL_PATHS_TEMPLATE: str = "DCC_MCP_USER_{}_SKILL_PATHS"
ENV_USER_SKILL_PATHS: str = "DCC_MCP_USER_SKILL_PATHS"

# ── SKILL.md metadata keys (per agentskills.io spec) ────────────────────────
# All extension keys must live under ``metadata.dcc-mcp.<feature>``.
METADATA_DCC_MCP: str = "dcc-mcp"
METADATA_RECIPES_KEY: str = f"{METADATA_DCC_MCP}.recipes"
METADATA_PROMPTS_KEY: str = f"{METADATA_DCC_MCP}.prompts"
METADATA_EXAMPLES_KEY: str = f"{METADATA_DCC_MCP}.examples"
METADATA_SKILL_REFERENCE_DOCS_KEY: str = f"{METADATA_DCC_MCP}.skill-reference-docs"
METADATA_WORKFLOWS_KEY: str = f"{METADATA_DCC_MCP}.workflows"
METADATA_LAYER_KEY: str = f"{METADATA_DCC_MCP}.layer"
METADATA_DCC_KEY: str = f"{METADATA_DCC_MCP}.dcc"
METADATA_VERSION_KEY: str = f"{METADATA_DCC_MCP}.version"
METADATA_TOOLS_KEY: str = f"{METADATA_DCC_MCP}.tools"
METADATA_GROUPS_KEY: str = f"{METADATA_DCC_MCP}.groups"
METADATA_SEARCH_HINT_KEY: str = f"{METADATA_DCC_MCP}.search-hint"
METADATA_TAGS_KEY: str = f"{METADATA_DCC_MCP}.tags"
METADATA_EXTERNAL_DEPS_KEY: str = f"{METADATA_DCC_MCP}.external-deps"

# ── SKILL layer taxonomy ────────────────────────────────────────────────────
# A skill's ``metadata.dcc-mcp.layer`` tag declares its architectural role.
LAYER_THIN_HARNESS: str = "thin-harness"
LAYER_DOMAIN: str = "domain"
LAYER_INFRASTRUCTURE: str = "infrastructure"
LAYER_EXAMPLE: str = "example"

# ── Tool categories ─────────────────────────────────────────────────────────
# Used as the ``category`` field on ``ToolRegistry.register(...)``.
CATEGORY_DIAGNOSTICS: str = "diagnostics"
CATEGORY_FEEDBACK: str = "feedback"
CATEGORY_INTROSPECT: str = "introspect"
CATEGORY_RECIPES: str = "recipes"
CATEGORY_WORKFLOWS: str = "workflows"
CATEGORY_DOCS: str = "docs"
CATEGORY_GENERAL: str = "general"

__all__ = [
    "CATEGORY_DIAGNOSTICS",
    "CATEGORY_DOCS",
    "CATEGORY_FEEDBACK",
    "CATEGORY_GENERAL",
    "CATEGORY_INTROSPECT",
    "CATEGORY_RECIPES",
    "CATEGORY_WORKFLOWS",
    "ENV_API_KEY",
    "ENV_ASSET",
    "ENV_ASSET_TYPE",
    "ENV_CONTEXT_BUNDLE",
    "ENV_CONTEXT_KIND",
    "ENV_CORE_VERSION",
    "ENV_CUA_ALLOW_RAW_INPUT",
    "ENV_CUA_BINARY",
    "ENV_DAEMONIZED",
    "ENV_DCC_EXCLUDE_STUBS_FROM_TOOLS_LIST_TEMPLATE",
    "ENV_DCC_INSTANCE_TYPE_TEMPLATE",
    "ENV_DCC_PORT_TEMPLATE",
    "ENV_DCC_SKILL_PATHS_TEMPLATE",
    "ENV_DCC_TYPE",
    "ENV_DEFAULT_TOOLS",
    "ENV_DEPLOYMENT_MODE",
    "ENV_DISABLE_ACCUMULATED_SKILLS",
    "ENV_DISABLE_DEFAULT_SKILL_PATHS",
    "ENV_DISABLE_FILE_LOGGING",
    "ENV_DISABLE_JOB_PERSISTENCE",
    "ENV_DISABLE_TELEMETRY",
    "ENV_EMBED_MODEL",
    "ENV_EMBED_MODEL_DIR",
    "ENV_EXCLUDE_STUBS_FROM_TOOLS_LIST",
    "ENV_GATEWAY_ADMIN_DB",
    "ENV_GATEWAY_ENSURE_TIMEOUT_SECS",
    "ENV_GATEWAY_GUARDIAN_FAILURES",
    "ENV_GATEWAY_GUARDIAN_INTERVAL",
    "ENV_GATEWAY_GUARDIAN_REENSURE_JITTER_MAX",
    "ENV_GATEWAY_GUARDIAN_RESTART_TIMEOUT",
    "ENV_GATEWAY_GUARDIAN_TIMEOUT",
    "ENV_GATEWAY_HOST",
    "ENV_GATEWAY_IDLE_TIMEOUT_SECS",
    "ENV_GATEWAY_LAUNCH_LOCK_STALE_SECS",
    "ENV_GATEWAY_NAME",
    "ENV_GATEWAY_PERSIST",
    "ENV_GATEWAY_PORT",
    "ENV_GATEWAY_PROBE_FAILURES",
    "ENV_GATEWAY_PROBE_INTERVAL",
    "ENV_GATEWAY_PROBE_TIMEOUT",
    "ENV_GUARDIAN_WATCHDOG_INTERVAL",
    "ENV_HOST_RPC",
    "ENV_INSTANCE_TYPE",
    "ENV_IPC_ADDRESS",
    "ENV_LOG_DIR",
    "ENV_MARKETPLACE_INSTALL_ROOT",
    "ENV_MCP_INSTALL_DIR",
    "ENV_MINIMAL",
    "ENV_PACKAGE_PROVENANCE",
    "ENV_PRODUCTION_DOMAIN",
    "ENV_PROJECT",
    "ENV_PROMPT_PATHS",
    "ENV_PYTHON_EXECUTABLE",
    "ENV_REGISTRY_DIR",
    "ENV_RESOURCE_PATHS",
    "ENV_REZ_LOCAL_CACHE_ROOT",
    "ENV_SCRIPT_MATERIALIZATION_ROOT",
    "ENV_SEQUENCE",
    "ENV_SERVER_BIN",
    "ENV_SHOT",
    "ENV_SKILL_PATHS",
    "ENV_STRICT_GATEWAY",
    "ENV_TASK",
    "ENV_TEAM_DCC_SKILL_PATHS_TEMPLATE",
    "ENV_TEAM_SKILL_PATHS",
    "ENV_TOOLSET_PROFILE",
    "ENV_UI_CONTROL_BACKEND",
    "ENV_UI_CONTROL_DCC_TYPE",
    "ENV_UI_CONTROL_PROCESS_ID",
    "ENV_UI_CONTROL_WINDOW_HANDLE",
    "ENV_USER_DCC_SKILL_PATHS_TEMPLATE",
    "ENV_USER_SKILL_PATHS",
    "LAYER_DOMAIN",
    "LAYER_EXAMPLE",
    "LAYER_INFRASTRUCTURE",
    "LAYER_THIN_HARNESS",
    "METADATA_DCC_KEY",
    "METADATA_DCC_MCP",
    "METADATA_EXAMPLES_KEY",
    "METADATA_EXTERNAL_DEPS_KEY",
    "METADATA_GROUPS_KEY",
    "METADATA_LAYER_KEY",
    "METADATA_PROMPTS_KEY",
    "METADATA_RECIPES_KEY",
    "METADATA_SEARCH_HINT_KEY",
    "METADATA_SKILL_REFERENCE_DOCS_KEY",
    "METADATA_TAGS_KEY",
    "METADATA_TOOLS_KEY",
    "METADATA_VERSION_KEY",
    "METADATA_WORKFLOWS_KEY",
]
